### ISSUE TITLE
Indexes in PalleteChunk.Colors don't match with actual color indexes in a pallete.

### ISSUE THREAD

**Issue by Silvian-73** [sandrofigo/VoxReader#2]
In MagicaVox palletes color indexes start from 1, but in PalleteChunk.Colors they start from 0. Indexes are shifted. Because of it, if I want to get a color with index i, I need to write palleteChunk.Color[i - 1]. This is counter intuitive and caused me a problem, because palleteChunk.Color[voxel.ColorIndex] doesn't give me a color of that voxel. Instead I have to write palleteChunk.Color[voxel.ColorIndex - 1]. That takes some time and nerves to understand. Please make color indexes start with 1 like in MagicaVox, so color indexes would match.

**Comment by sandrofigo** [comment]
I will consider this in the next version.

**Comment by sandrofigo** [comment]
There was a bug that may have shifted the indices of the palette colors by 1. In version 2.0.0 the colors of the palette are accessible through `Color[] colors = voxFile.Palette.Colors;`.

This has been resolved with 952e3e2fc00db434244ff2786875b476b8aba699
