### ISSUE TITLE
About credit for your work

### ISSUE THREAD

**Issue by SwatDoge** [sandrofigo/VoxReader#22]
Hello!

I've used this tool in a game server plugin, where it is responsible for loading in custom terrain from magica voxel. In order to load this plugin, users need to drop my plugin in a folder as .dll, however they also need to put in voxreader.dll for it to work.

Right now, I've published both our dll's under one release like such: https://github.com/SwatDoge/SOTTBBVFMVTAEBP/releases/tag/1.0.0 and credited accordingly. I've mostly done this for convenience.

Do you feel this is sufficient crediting? Would you prefer me to delete the voxreader.dll, and refer users to this github?

I apologize for publishing your code, I am still figuring out the best way to do this.

**Comment by sandrofigo** [comment]
Hi @SwatDoge,

thank you for reaching out about the license. I released VoxReader under the MIT license.

This means that the copyright notice "Copyright (c) 2022 Sandro Figo" and the permission notice (the license text from [here](https://github.com/sandrofigo/VoxReader/blob/develop/LICENSE.md)) must be included in your software.

You can still distribute the .dll how you want, but you need to include the copyright notice and license mentioned above somewhere (e.g.  include the [VoxReader license file](https://github.com/sandrofigo/VoxReader/blob/develop/LICENSE.md) in the assets of your GitHub Release (https://github.com/SwatDoge/SOTTBBVFMVTAEBP/releases)).

Linking back to my repository in your README or somewhere else is optional, but appreciated.
