### ISSUE TITLE
Voxel Index Out Of Bounds

### ISSUE THREAD

**Issue by STCollier** [sandrofigo/VoxReader#26]
Hello,

This seems really strange but for some reason it doesn't appear that I can index each voxel within a model. I have this snippet of code:
```cs
        IModel[] models = voxFile.Models;
        Voxel[] voxels = models[0].Voxels;

        int max = models[0].Size.X * models[0].Size.Y * models[0].Size.Z;
        Debug.Log(voxels[max]); // IndexOutOfRangeException: Index was outside the bounds of the array.
```
This throws an `IndexOutOfRangeException` and I believe this is wrong.

**Comment by sandrofigo** [comment]
This is indeed odd at first glance.

The length of the voxels array is using a zero based index, this means when you have for example a simplified model with the dimensions of X: 2 Y: 2 and Z: 2 the total voxel count would be 8 and to access the last voxel in the array you would need to use `voxels[7]`.

In your particular case you would need to use `Debug.Log(voxels[max - 1]);`, since you need to subtract 1 from the total amount of voxels in the array.

Let me know if it works.

**Comment by STCollier** [comment]
Thanks for the response. Yes, I suspected that and it still doesn't seem to work. I've tried even subtracting a random large number like `max - 100` and it doesn't work. If it helps, this is the full code and vox file I'm using:
```cs
        IVoxFile voxFile = VoxReader.VoxReader.Read("Assets/Models/vox/teapot.vox");
        if (voxFile == null) Debug.Log("Failed to load vox file!");

        IModel[] models = voxFile.Models;
        Voxel[] voxels = models[0].Voxels;

        int max = models[0].Size.X * models[0].Size.Y * models[0].Size.Z;
        Debug.Log(voxels[max - 1]);
```
[teapot.vox.zip](https://github.com/user-attachments/files/18187152/teapot.vox.zip)
Any ideas?

**Comment by sandrofigo** [comment]
Thanks for providing a model I can test with. I'll take a closer look at it as soon as possible.

**Comment by sandrofigo** [comment]
Ok, I was always thinking with the test files in mind I created some time ago where the model was filled completely with voxels (sorry for that oversight). In your case you have "air" in the model and thus the voxel array length is smaller then the calculated max voxel count the model could have.

In your particular case it should be possible to get the last voxel in the array with `Debug.Log(voxels[voxels.Length - 1]);`

If you want to iterate e.g. all voxels you can use something like this:

```csharp
for (int i = 0; i < voxels.Length; i++)
{
    Debug.Log(voxels[i]);
}
```

**Comment by STCollier** [comment]
Thanks so much! That makes much more sense now.
