### ISSUE TITLE
Add support to get model positions

### ISSUE THREAD

**Issue by rbxrootx** [sandrofigo/VoxReader#7]
I'm working with .vox files, and I noticed there isn't a way to get the position of a group, the cars.vox file included with magicavoxel, has two groups which can be seen below, however when I parse the voxels using voxelReader and since there's no group positions, the voxels all occupy the same space.

![image](https://user-images.githubusercontent.com/22184962/210195280-6f03acb8-3209-4602-9a4f-f4373af4c8cf.png)
,

**Comment by sandrofigo** [comment]
I'm going to add this feature with the next release and will post any updates here.

**Comment by rbxrootx** [comment]
Great thank you so much!

**Comment by sandrofigo** [comment]
@rbxrootx This feature is now included in the [v3.0.0](https://github.com/sandrofigo/VoxReader/releases/tag/v3.0.0) release.
Let me know if you encounter any bugs.

**Comment by sandrofigo** [comment]
@rbxrootx The voxel position has not changed, but you are now able to add the `Position` property from the `Model` to get the global voxel position. Please note that the model position in MagicaVoxel is located at the center of each model, you might have to take the model width and height into account for the correct position.

I will probably add a helper function in a future version soon™️

**Comment by sandrofigo** [comment]
With #13 all voxels have a new global position property.
