### ISSUE TITLE
KeyNotFoundException when parsing specific .vox files

### ISSUE THREAD

**Issue by rbxrootx** [sandrofigo/VoxReader#8]
**KeyNotFoundException when parsing specific .vox files**
I am experiencing a KeyNotFoundException when attempting to parse certain .vox files. The error message is:

`System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'`

I have tried parsing several .vox files and have found that some of them work as expected, while others do not. I have not been able to identify any specific pattern or cause for the files that are causing this exception to be thrown.

I have attached a **.zip** of the vox file below, when parsing this file you will be presented with the error above:

[Example.zip](https://github.com/sandrofigo/VoxReader/files/10332997/titanic.zip)

Any help or guidance on this issue would be greatly appreciated. Thank you!

**Comment by sandrofigo** [comment]
Thank you for bringing this up!
If I try to read the provided file I get the error `The given key 'IMAP' was not present in the dictionary.` It seems like I forgot to parse 'IMAP' chunks 😅 

I will push a bug fix version as soon as possible.

**Comment by sandrofigo** [comment]
@rbxrootx this should be fixed with v2.1.2
